server:
  addr:
  port: 8080
  read_timeout: 5
  write_timeout: 10
  env: production

database:
  host: "localhost"
  port: 3306
  dbname: "order_db"
  user: "order_admin"
  password: "order798"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 5m
  time_zone: "Asia/Shanghai"
  schema_file: "internal/config/schema.sql"

cache:
  type: redis
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
  max_size: 1000
  expiration: 3600

log:
  format: json           # 日志格式，可选值: text, json
  output: stdout         # 日志输出方式，可选值: stdout（标准输出）或 file（文件输出）
  level: "debug"          # 日志级别，可选值: debug, info, warn, error, fatal
  file: "logs/app.log"   # 日志文件路径，仅在 output 设置为 file 时生效
  max_size: 10           # 单个日志文件的最大大小（单位 MB），超出后会创建新文件
  max_backups: 5         # 最多保留的历史日志文件数，超过此数量则删除最旧的日志文件
  max_age: 7             # 日志文件最大保存天数，超过后自动删除旧日志
  compress: true         # 是否压缩旧的日志文件（gzip 压缩）